name: PITI
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py37h06a4308_2
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py37h7b6447c_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.1.0=pyhd3eb1b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - locket=0.2.1=py37h06a4308_1
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.5.0=py37h3ed280b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.2.2=py37h06a4308_0
  - protobuf=3.17.2=py37h295c915_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scipy=1.7.3=py37hc147768_0
  - setuptools=58.0.4=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.11.1=py37_cu113
  - tornado=6.1=py37h27cfd23_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - analytics-python==1.4.0
    - anyio==3.6.1
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.1.0
    - backoff==1.10.0
    - bcrypt==3.2.2
    - blobfile==1.2.7
    - cached-property==1.5.2
    - cffi==1.15.1
    - charset-normalizer==2.0.9
    - click==8.1.3
    - cryptography==37.0.4
    - dlib==19.22.1
    - einops==0.4.1
    - fastapi==0.79.0
    - ffmpy==0.3.0
    - filelock==3.4.0
    - fonttools==4.28.3
    - frozenlist==1.3.0
    - ftfy==6.0.3
    - h11==0.12.0
    - h5py==3.6.0
    - httpcore==0.15.0
    - httpx==0.23.0
    - idna==3.3
    - imageio==2.13.3
    - imgaug==0.4.0
    - importlib-metadata==4.12.0
    - jinja2==3.1.2
    - kiwisolver==1.3.2
    - linkify-it-py==1.0.3
    - lmdb==1.2.1
    - markdown-it-py==2.1.0
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.1
    - monotonic==1.6
    - mpi4py==3.0.3
    - multidict==6.0.2
    - opencv-python==4.5.4.60
    - orjson==3.7.11
    - pandas==1.3.5
    - paramiko==2.11.0
    - pyaml==21.10.1
    - pycparser==2.21
    - pycryptodome==3.15.0
    - pycryptodomex==3.12.0
    - pydantic==1.9.1
    - pydub==0.25.1
    - pynacl==1.5.0
    - pyparsing==3.0.6
    - python-multipart==0.0.5
    - pytorch-fid==0.2.1
    - pytz==2022.1
    - pywavelets==1.2.0
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.26.0
    - rfc3986==1.5.0
    - scikit-image==0.19.0
    - shapely==1.8.0
    - sniffio==1.2.0
    - starlette==0.19.1
    - tifffile==2021.11.2
    - timm==0.4.12
    - tqdm==4.62.3
    - uc-micro-py==1.0.1
    - urllib3==1.26.7
    - uvicorn==0.18.2
    - wcwidth==0.2.5
    - xmltodict==0.12.0
    - yarl==1.7.2
    - zipp==3.8.1
 
